# docker compose
version: '3'
# docker run -d --name pwdtest2 -p 9023:80 -v ./mysql:/opt/sqlback pwdtest2


services:
  pwdgen:
    build: .
    container_name: pwdgen
    ports:
      - "9023:80"
    volumes:
      - ./mysql:/opt/sqlback pwdtest2
    restart: always
