version: '3'
services:
  web:
    build: .
    container_name: pwd-web
    ports:
      - "8081:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: pwd-db
    environment:
      MYSQL_ROOT_PASSWORD: thisisasecurepasswordright?right?
      MYSQL_DATABASE: pwdgen
      MYSQL_USER: pwd
      MYSQL_PASSWORD: BaDA9rAarBNpPSwc
#   to restore with full hash data, change to pwdgen-hash from just pwdgen in the volume here
    volumes:
      - ./sql/pwdgen.sql:/docker-entrypoint-initdb.d/init.sql
