# docker compose
version: '3'
# docker run -d --name pwd.theregion.beer -p 8503:80 -v ./mysql:/opt/sqlback pwdgen


services:
  pwdgen:
    build: .
    image: pwdgen:latest
    container_name: pwd.theregion.beer
    ports:
      - "8503:80"
    volumes:
      - ./mysql:/opt/sqlback
    restart: always
