version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: thisisasecurepasswordright?right?
      MYSQL_DATABASE: pwdgen
      MYSQL_USER: pwd
      MYSQL_PASSWORD: BaDA9rAarBNpPSwc
    volumes:
      - ./sql/pwdgen.sql:/docker-entrypoint-initdb.d/init.sql
